#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check prettier standards
npm run check-format ||
echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
Prettier Check Failed. Run npm run format, add changes and try commit again.'
false;

npm run check-lint ||
echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
false; 

npm run check-types ||
echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
Are you seriously still writing JS? Make the changes required above.'
false;

echo '🤔🤔🤔🤔... You win this time. Code looks good to me... Committing now. 🤔🤔🤔🤔'